treewide: bash scripts improvements
also add formatter script
Signed-off-by: Nauval Rizky <enuma.alrizky@gmail.com>

diff --git a/bin/rom-mount b/bin/rom-mount
--- a/bin/rom-mount
+++ b/bin/rom-mount
@@ -11,36 +11,45 @@
 
 TARGET=$1
 
+log() {
+    TAG=$(basename $0)
+    printf "$TAG: %s\n" "$1"
+}
+
 dump() {
     file=$1
     targetmount=$2
     if [[ -f $file.new.dat.br ]]; then
-        echo ":: decompressing $file"
+        log "decompressing $file"
         brotli --decompress $file.new.dat.br
         sdat2img $file.transfer.list $file.new.dat $file.img
         rm -rf $file.{new.dat.br,new.dat,transfer.list,patch.dat}
-        echo ":: decompressing $file done"
+        log "decompressing $file done"
     fi
     if [[ -f $file.img ]]; then
         mkdir -p $targetmount
-        echo ":: mounting $file into $targetmount"
+        log "mounting $file into $targetmount"
         sudo mount $file.img $targetmount
         sudo chown -hR "$USER:users" $targetmount
-        echo ":: mounting $file done"
+        log "mounting $file done"
     fi
 }
 
-if ! ls $(pwd) | grep -qE '(vendor|system)\.(img|new\.dat\.br)'; then
-    echo ":: no system or vendor images to extract, exiting"
-    exit
-fi
+main() {
+    if ! ls $(pwd) | grep -qE '(vendor|system)\.(img|new\.dat\.br)'; then
+        log "no system or vendor images to extract, exiting"
+        exit 1
+    fi
 
-if [[ "$TARGET" == "" ]]; then
-    echo ":: target is empty, please run $(basename $0) <target-dir>"
-elif [[ ! -d "$TARGET" ]]; then
-    echo ":: target directory not found, creating ones"
-    mkdir $TARGET
-fi
+    if [[ $TARGET == "" ]]; then
+        log "target is empty, please run $(basename $0) <target-dir>"
+    elif [[ ! -d $TARGET ]]; then
+        log "target directory not found, creating ones"
+        mkdir $TARGET
+    fi
 
-dump system $TARGET
-dump vendor $TARGET/vendor
+    dump system $TARGET
+    dump vendor $TARGET/vendor
+}
+
+main $0
